# Generated by Django 2.0.5 on 2019-04-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiar', models.BooleanField(default=False)),
                ('veneficiario', models.BooleanField(default=False)),
                ('profesorado', models.BooleanField(default=False)),
                ('comunicaciones', models.BooleanField(default=False)),
                ('administracion', models.BooleanField(default=False)),
                ('contaduria', models.BooleanField(default=False)),
                ('computacion', models.BooleanField(default=False)),
                ('juridica', models.BooleanField(default=False)),
                ('teologia', models.BooleanField(default=False)),
                ('nombre', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
                ('institucion_actual', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
                ('comentario', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
            ],
        ),
    ]
